export { default as ProfileStats } from './ProfileStats.vue'
export { default as DailyNutritionStats } from './DailyNutritionStats.vue'
export { default as MealsList } from './MealsList.vue'
export { default as CryptoPayment } from './Payment.vue'
export { default as PaymentMethodSelector } from './PaymentMethodSelector.vue'
